// Code generated by "stringer -type=Change"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unchanged-0]
	_ = x[Added-1]
}

const _Change_name = "UnchangedAdded"

var _Change_index = [...]uint8{0, 9, 14}

func (i Change) String() string {
	if i < 0 || i >= Change(len(_Change_index)-1) {
		return "Change(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Change_name[_Change_index[i]:_Change_index[i+1]]
}
