// Code generated by "stringer -type=change,changedStats"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unchanged-1]
	_ = x[added-2]
	_ = x[statsChanged-3]
}

const _change_name = "unchangedaddedstatsChanged"

var _change_index = [...]uint8{0, 9, 14, 26}

func (i change) String() string {
	i -= 1
	if i < 0 || i >= change(len(_change_index)-1) {
		return "change(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _change_name[_change_index[i]:_change_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[changedModTime-1]
	_ = x[changedSize-2]
}

const _changedStats_name = "changedModTimechangedSize"

var _changedStats_index = [...]uint8{0, 14, 25}

func (i changedStats) String() string {
	i -= 1
	if i < 0 || i >= changedStats(len(_changedStats_index)-1) {
		return "changedStats(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _changedStats_name[_changedStats_index[i]:_changedStats_index[i+1]]
}
